### ISSUE TITLE
conditional compilation problem

### ISSUE THREAD

**Issue by cherouvim** [yui/yuicompressor#119]
The compressor breaks on:
if (/_@cc_on!@_/true) alert(2);

with:
missing ) after condition

This kind of code exists in selectivizr.com

**Comment by marczych** [comment]
I just ran into this as well and boiled it down to this example:

```js
var x = /*@cc_on/*@if(@_jscript_version<=5.7)true@else@*/false/*@end@*/;
```

```
[mzych@home] - [~] - [Thu Oct 08, 04:58:31]
[N]> java -jar yuicompressor-2.4.8.jar --type js --charset utf-8  <(echo "var x = /*@cc_on/*@if(@_jscript_version<=5.7)true@else@*/false/*@end@*/;")
[ERROR] in /proc/self/fd/11
  1:63:missing ; before statement
[ERROR] in /proc/self/fd/11
  1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
[mzych@home] - [~] - [Thu Oct 08, 04:58:45] - [2]
[I]> java -jar yuicompressor-2.4.8pre.jar --type js --charset utf-8  <(echo "var x = /*@cc_on/*@if(@_jscript_version<=5.7)true@else@*/false/*@end@*/;")
var x=
/*@cc_on/*@if(@_jscript_version<=5.7)true@else@*/
false
/*@end@*/;%                                                                                                                                                                                                                                                                                   [mzych@cominor] - [~] - [Thu Oct 08, 04:59:02]
[I]> java -jar yuicompressor-2.4.8pre.jar --version

Usage: java -jar yuicompressor-2.4.6.jar [options] [input file]

Global Options
  -h, --help                Displays this information
  --type <js|css>           Specifies the type of the input file
  --charset <charset>       Read the input file using <charset>
  --line-break <column>     Insert a line break after the specified column number
  -v, --verbose             Display informational messages and warnings
  -o <file>                 Place the output into <file>. Defaults to stdout.
                            Multiple files can be processed using the following syntax:
                            java -jar yuicompressor.jar -o '.css$:-min.css' *.css
                            java -jar yuicompressor.jar -o '.js$:-min.js' *.js

JavaScript Options
  --nomunge                 Minify only, do not obfuscate
  --preserve-semi           Preserve all semicolons
  --disable-optimizations   Disable all micro optimizations

If no input file is specified, it defaults to stdin. In this case, the 'type'
option is required. Otherwise, the 'type' option is required only if the input
file extension is neither 'js' nor 'css'.
```

Note that a similar code snippet is found in [FileDrop](https://github.com/ProgerXP/FileDrop/blob/33f85ce84a1df890ab5d9dcf6d105c457b2f18b0/filedrop.js#L568-L569).

Is there fix or workaround in the works?

**Comment by timothyasp** [comment]
One less than ideal solution is to just make a change do our fork of filedrop here - https://github.com/iFixit/FileDrop/blob/master/filedrop.js#L569.

We could use `/\bMSIE 6/.test(navigator.userAgent)` for `isIE6` and `/\bMSIE 9/.test(navigator.userAgent)`
