### ISSUE TITLE
 Bad source throw new RuntimeException(); 300 line

### ISSUE THREAD

**Issue by wchaowu** [yui/yuicompressor#173]
java.lang.StringIndexOutOfBoundsException: String index out of range: 1573
    at java.lang.String.substring(String.java:1907)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSourceString(JavaScriptCompressor.java:269)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:333)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)

**Comment by qsiebers** [comment]
Same issue here, not excluding js-R1.7 will causes exceptions because a web based classloader prefers the js-R1.7.jar classes over the classes contained in the yuicompressor jar.

**Comment by markkolich** [comment]
+1 here.

```
[INFO] |  \- com.yahoo.platform.yui:yuicompressor:jar:2.4.8:compile
[INFO] |     \- rhino:js:jar:1.7R2:compile
```

Although this works, I'm a little weary of adding an exclusion to keep `rhino:js:1.7R2` out of the dependency tree:

```xml
<dependency>
  <groupId>com.yahoo.platform.yui</groupId>
  <artifactId>yuicompressor</artifactId>
  <version>2.4.8</version>
  <exclusions>
      <exclusion>
          <groupId>rhino</groupId>
          <artifactId>js</artifactId>
      </exclusion>
  </exclusions>
</dependency>
```

What's the reason for shadowing the `rhino:js` classes inside of the YUI artifact?  If they're shadowed correctly, there should be no need to declare a `compile` dependency on `rhino:js` directly.
