### ISSUE TITLE
Compressor breaks on empty files

### ISSUE THREAD

**Issue by sippsolutions** [yui/yuicompressor#176]
YUIC breaks on js files containing only a comment.

Example: test.js
```
// this is a sample js file
```

Called YUIC via ANT:
```
    [apply] Exception in thread "main" java.lang.reflect.InvocationTargetException
    [apply] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [apply] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [apply] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [apply] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [apply] 	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
    [apply] Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    [apply] 	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    [apply] 	at java.util.ArrayList.get(ArrayList.java:411)
    [apply] 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.getToken(JavaScriptCompressor.java:578)
    [apply] 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSymbolTree(JavaScriptCompressor.java:1094)
    [apply] 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.compress(JavaScriptCompressor.java:556)
    [apply] 	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:186)
    [apply] 	... 5 more
```

- OS X 10.10
- YUIC 2.4.8
- Java 1.7.0_72

**Comment by tml** [comment]
@betesh Indeed it does.
