### ISSUE TITLE
2.4.8 fails with CKEditor 3.6.6.2

### ISSUE THREAD

**Issue by gerdriesselmann** [yui/yuicompressor#178]
Compressing ckeditor.js of CKEditor version 3.6.6.2 fails with the following errors:

```
[ERROR] in ckeditor.js
  7:1375:missing } after property list
[ERROR] in ckeditor.js
  7:1734:missing ) in parenthetical
[ERROR] in ckeditor.js
  153:1316:syntax error
[ERROR] in ckeditor.js
  1:0:Compilation produced 3 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 3 syntax errors.
    at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
    at org.mozilla.javascript.Parser.parse(Parser.java:396)
    at org.mozilla.javascript.Parser.parse(Parser.java:340)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
    at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

Command line was

```
java -jar yuicompressor.jar --type js --charset utf-8 --line-break 1000 -o out.js ckeditor.js
```

It works with older versions of YUI Compressor, though

**Comment by PeterDaveHello** [comment]
I think yuicompressor fails on many libs, but that libs in fact are not invalid, works with other minifier.
