### ISSUE TITLE
Problem with property named this.package

### ISSUE THREAD

**Issue by joni2back** [yui/yuicompressor#182]
There are a strange error compressing this part of code, the problem is using a property named "package"
I know "package" is a reserved word, but in this case, is the name of a property of the class (not a single var)

```js
define(['knockout', 'package'], function(ko, Package) {
    var MyClass = function(data) {
        var self = this;
        self.package = ko.observable(new Package());  //line 5329
        ko.mapping.fromJS(data, {}, self);
    };
    return MyClass;
});
```
```
[ERROR] in web/application/assets/built/require.build.dhm.js
  5329:21:missing name after . operator
[ERROR] in web/application/assets/built/require.build.dhm.js
  1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

**Comment by tml** [comment]
Tracking all versions of this issue on #47, closing the rest so that I only have one bug to keep track of for all the variants of the problem.
