### ISSUE TITLE
Unable to run tests on MacOS

### ISSUE THREAD

**Issue by dtsn** [yui/yuicompressor#188]
Hi Everyone,

I am trying to run the test suite for a possible fix to issue #141 however I can't seem to get it to work on my Mac. Anyone have any ideas?

`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
Caused by: java.lang.StackOverflowError`

**Comment by tml** [comment]
Are you running this with your proposed change to the CssCompressor.java in place? I have this same issue when modifying the regex for data URIs, but it runs just fine for me on OS X 10.8 and 10.9 without that proposed change in place.

**Comment by dtsn** [comment]
@tml I am running it on a vanilla install of master and i'm getting the error without any of my changes. I have also tried 2.4.8 and while i am not getting the java error the tests are failing on `_munge.js`.

I can see this tests are working on Travis, so it must be something on my machine. I'll keep investigating, thanks for your help.
