### ISSUE TITLE
Fails on accessing object property

### ISSUE THREAD

**Issue by lokeb** [yui/yuicompressor#190]
My script fails to compile when the property is accessed using the dot operator and succeeds when used using the array syntax. The following line is found in my script at line 78. A very unusual problem:

Problematic code:
images[i].style['float'] = 'left'; //works
images[i].style.float = 'left'; //Fails

Error log:
[ERROR] in framework.js
  78:24:missing name after . operator
[ERROR] in framework.js
  1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
    at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
    at org.mozilla.javascript.Parser.parse(Parser.java:396)
    at org.mozilla.javascript.Parser.parse(Parser.java:340)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
    at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

**Comment by tml** [comment]
Not strange at all, as `float` is not a valid property name in ES3. Same as issue #47.
