### ISSUE TITLE
"let" statement causing Exception in thread main

### ISSUE THREAD

**Issue by quentinHydrobat** [yui/yuicompressor#259]
Hi everyone, here the cmd : 
`yui-compressor ./public/js/objectList/base.js -o ./public/js/objectList/base.min.js --charset utf-8 --type js`

Here the file : 
```
if (typeof object === 'undefined') {
	var object = {};

	object.data = {
		loadedPoint: 0,
		loader: 0
	};

	object.init = function(force) {
		return object.initer.init(force);
	};

	object.log = function(ln, data, filename) {
		if (!dev) {
			return dev;
		};
		data = (typeof data === "undefined" ? false : data);
		if (typeof data != "object" && typeof data != "array" && typeof data != "function") {
			console.log(filename+" : line " + ln + ' | '+this.log.caller.caller.name+'()'+(data ? ' :  ' + data : ''));
		} else {
			console.log(filename+" : line " + ln + ' | '+this.log.caller.caller.name+'()'+(data ? ' : ' : ''));
			console.log(data);
		};
		return dev;
	};
	object.warn = function(ln, data, filename) {
		data = (typeof data === "undefined" ? false : data);
		if (typeof data != "object" && typeof data != "array" && typeof data != "function") {
			console.warn(filename+" : line " + ln + ' | '+this.warn.caller.caller.name+'()'+(data ? ' :  ' + data : ''));
		} else {
			console.warn(filename+" : line " + ln + ' | '+this.warn.caller.caller.name+'()'+(data ? ' :  ' : ''));
			console.warn(data);
		};
		return dev;
	};
}

object.initer = {
	log: function(ln, data){
		object.log(ln, data, 'objectList/base.js');
	},
	warn: function(ln, data){
		object.warn(ln, data, 'objectList/base.js');
	},
	data: {
		merge:[],
		propertie:[]
	},
	/**
	 * Charge tout les infos necessaire et affiche le tableau des objectList
	 */
	init: function(force){
		this.log(ln());

		force = (typeof force === 'undefined' ? false : force);
		object.data.loadedPoint = 0;
		object.data.loader = 2;

		// on montre le chargement
		loadingToast.open('Récupération des données ...&nbsp;<a class="white-text" id="percent">0%</a>', 'initer');
		object.render.displayLoadingInListTable();

		// on récupère tout les object
		object.get.allObjectByTable({}, function(objList){
			if (!objList) {
				Materialize.toast('<i class="material-icons left">error</i> Impossible de charger la liste des objets.'
					+' Veuillez contacter votre administrateur système.', 2500, 'error');
				object.data.loadedPoint = object.data.loader;
				return false;
			}
			object.initer.data.merge = objList;
			// on va devoir aller chercher toutes les variables pour chaque object, donc on modifie le nombre de loader
			object.data.loader += objList.length;
			++object.data.loadedPoint;
			// pour éviter d'afficher l'erreur de chargement en millions d'exemplaire xD
			var alarm = true;
			for (var i = objList.length - 1; i >= 0; i--) {
				let elem = objList[i];
				object.get.asyncAllLastVarByTableAndObjectId({
					__OBJECT_ID:elem.id
				}, function(vars) {
					if (!vars || vars.length <= 0) {
						if (alarm) { // affichage de l'erreur UNE FOIS si l'un des chargement est incomplet.
							alarm = false;
							Materialize.toast('<i class="material-icons left">error</i> Certains objets sont incomplet.'
								+' Veuillez contacter votre administrateur système.', 2500, 'error');
						}
					}
					elem.vars = [];
					for (var i = vars.length - 1; i >= 0; i--) {
						if (vars[i].object_id == elem.id) {
							elem.vars.push(vars[i]);
						}
					}
					++object.data.loadedPoint;
				});
			}
		}, force);

		object.get.allPropertieByTable({}, function(propList){
			if (!propList) {
				Materialize.toast('<i class="material-icons left">error</i> Impossible de charger la liste des objets.'
					+' Veuillez contacter votre administrateur système.', 2500, 'error');
				return false;
			}
			++object.data.loadedPoint;
			object.initer.data.propertie = propList;
			object.render.tablePropertie(propList, true);
		}, force);

		var interval = setInterval(function(){
			$('#percent').html(parseInt(object.data.loadedPoint * 100 / object.data.loader)+"%");
			if (object.data.loadedPoint >= object.data.loader) {
				clearInterval(interval);
				object.initer.mergeData();
				loadingToast.close('initer');
				object.render.tableObject(object.initer.data.merge, true);
				object.listener.setListener();
				if (object.initer.data.propertie.length <= 0) {
					object.render.modalMustAddPropertie();
				}
			};
		}, 100);
	},
	/**
	 * Le lien entre prop et value est déjà fait par la view object_var
	 * on doit combler les trou pour les prop sans value est assurer un affichage correcte
	 */
	mergeData: function(){
		this.log(ln());
		// boucle des objet
		for (var i = object.initer.data.merge.length - 1; i >= 0; i--) {
			let obj = object.initer.data.merge[i];
			// boucle des propriétés
			for (var k = object.initer.data.propertie.length - 1; k >= 0; k--) {
				let prop = object.initer.data.propertie[k];
				let isHere = false; // est-ce que la prop existe dans l'objet
				// boucle sur les values de l'objet
				for (var j = obj.vars.length - 1; j >= 0; j--) {
					let obj_var = obj.vars[j];
					if (obj_var.object_propertie_id == prop.id) { // si oui
						isHere = true;
					}
				}
				// si la propriété n'existe pas pour cet objet, on l'ajoute à valeur == null
				if (!isHere) {
					object.initer.warn(ln(), "object "+object.initer.data.merge[i].id+" does not contain prop "+object.initer.data.propertie[k].id);
					object.initer.data.merge[i].vars.push({
						id                  : false,
						time                : 0,
						creator_id          : 1,
						value               : '<span class="red-text">N/A</span>',
						object_propertie_id : prop.id,
						object_id           : obj.id,
						propertie_creator   : prop.creator_id,
						propertie_time      : prop.time,
						object_table        : prop.table,
						ordre               : prop.ordre,
						type                : prop.type,
						codename            : prop.codename,
						displayname         : prop.displayname,
						description         : prop.description,
						hide                : prop.hide
					});
				}
			}
			// on retri les propriété pour être sûr qu'elle s'afficheront dans l'ordre
			object.initer.data.merge[i].vars = object.initer.data.merge[i].vars.sort(function(a, b){
				return b.ordre-a.ordre;
			});
		}
	}
};
```

Here the error : 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale fr_FR
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at org.mozilla.javascript.ScriptRuntime$DefaultMessageProvider.getMessage(ScriptRuntime.java:3608)
	at org.mozilla.javascript.ScriptRuntime.getMessage(ScriptRuntime.java:3592)
	at org.mozilla.javascript.ScriptRuntime.getMessage0(ScriptRuntime.java:3540)
	at org.mozilla.javascript.Parser.addError(Parser.java:145)
	at org.mozilla.javascript.Parser.reportError(Parser.java:160)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1285)
	at org.mozilla.javascript.Parser.statement(Parser.java:726)
	at org.mozilla.javascript.Parser.statements(Parser.java:674)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1164)
	at org.mozilla.javascript.Parser.statement(Parser.java:726)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:950)
	at org.mozilla.javascript.Parser.statement(Parser.java:726)
	at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:482)
	at org.mozilla.javascript.Parser.function(Parser.java:611)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:2255)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:1974)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:1832)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:1761)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:1742)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:1722)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:1696)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:1652)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:1641)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:1630)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:1619)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:1607)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:1595)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:1578)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:1563)
	at org.mozilla.javascript.Parser.argumentList(Parser.java:1929)
	at org.mozilla.javascript.Parser.memberExprTail(Parser.java:2069)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:1977)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:1832)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:1761)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:1742)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:1722)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:1696)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:1652)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:1641)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:1630)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:1619)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:1607)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:1595)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:1578)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:1563)
	at org.mozilla.javascript.Parser.expr(Parser.java:1542)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1221)
	at org.mozilla.javascript.Parser.statement(Parser.java:726)
	at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:482)
	at org.mozilla.javascript.Parser.function(Parser.java:611)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:2255)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:1974)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:1832)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:1761)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:1742)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:1722)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:1696)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:1652)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:1641)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:1630)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:1619)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:1607)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:1595)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:1578)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:1563)
	at org.mozilla.javascript.Parser.plainProperty(Parser.java:2502)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:2374)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:1974)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:1832)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:1761)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:1742)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:1722)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:1696)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:1652)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:1641)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:1630)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:1619)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:1607)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:1595)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:1578)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:1563)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:1569)
	at org.mozilla.javascript.Parser.expr(Parser.java:1542)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1221)
	at org.mozilla.javascript.Parser.statement(Parser.java:726)
	at org.mozilla.javascript.Parser.parse(Parser.java:420)
	at org.mozilla.javascript.Parser.parse(Parser.java:378)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:131)
	... 5 more
```

If I replace every `let` by `var` everything is fine ...

**Comment by quentinHydrobat** [comment]
yui was installed with `apt install yui-compressor` it's seems yui was not the latest version (?)
Just installed manually from https://github.com/yui/yuicompressor/releases (2.4.8) 

This errors disappear, new errors appears : 
- empty file error https://github.com/yui/yuicompressor/issues/130 
- Naming an object `import` is causing syntax error https://github.com/yui/yuicompressor/issues/250

Closed
