### ISSUE TITLE
Doesn't Support JavaScript (ES6/ES2015)?

### ISSUE THREAD

**Issue by 772807886** [yui/yuicompressor#262]

**Comment by LeiZeng** [comment]
Hope it helps.
https://gist.github.com/LeiZeng/535de7c66f1a847c7bf80705098ea517

**Comment by Chris2011** [comment]
As you can see it here: https://github.com/Chris2011/js-css-minify-compress the yui-compressor.jar is using as a wrapped lib for a plugin for NetBeans to compress JS files for example. It gives me thos output:

````
org.mozilla.javascript.EvaluatorException: Compilation produced 14 syntax errors.
	at org.netbeans.util.source.minify.MinifyUtil$CompressorErrorReporter.runtimeError(MinifyUtil.java:485)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at org.netbeans.util.source.minify.MinifyUtil.compress(MinifyUtil.java:371)
	at org.netbeans.util.source.minify.JSMinify.jsMinify(JSMinify.java:99)
	at org.netbeans.util.source.minify.JSMinify.access$000(JSMinify.java:47)
	at org.netbeans.util.source.minify.JSMinify$1.run(JSMinify.java:65)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
````

when I try to minify this file: http://honlapgyartok.hu/sandbox/FrameworkShared/js/Webbi/Plugin/FormBuilder.js

**Comment by Chris2011** [comment]
It happens here: 

```
$(e).on('click', function(
   var id = SELF._getFormId(ev.target);
                                               SELF.export(id);
                                        });
```

**Comment by Chris2011** [comment]
Anything new here? Please add ES6 support.

**Comment by Chris2011** [comment]
Progress?

**Comment by valentinbdv** [comment]
+1 would be great to have ES6 support!

**Comment by zetekla** [comment]
add support for Webpack, Browserify and better yet ES6 altogether pls.

**Comment by sjtower** [comment]
We'll be dropping YUI unless it can support ES6 soon

**Comment by mostafamiri65** [comment]
Does not support for ECMA6?
```
[ERROR] in DataTables.js
  1:6:identifier is a reserved word
[ERROR] in DataTables.js
  4:31:syntax error
[ERROR] in DataTables.js
  139:42:missing ) after formal parameters
[ERROR] in DataTables.js
  139:42:missing } after function body
[ERROR] in DataTables.js
  148:47:syntax error
[ERROR] in DataTables.js
  171:13:syntax error
[ERROR] in DataTables.js
  173:30:missing ; before statement
[ERROR] in DataTables.js
  175:56:missing ; before statement
[ERROR] in DataTables.js
  177:25:syntax error
[ERROR] in DataTables.js
  206:17:syntax error
[ERROR] in DataTables.js
  226:13:syntax error
[ERROR] in DataTables.js
  228:19:syntax error
[ERROR] in DataTables.js
  230:19:syntax error
[ERROR] in DataTables.js
  239:13:syntax error
[ERROR] in DataTables.js
  356:9:syntax error
[ERROR] in DataTables.js
  358:15:invalid return
[ERROR] in DataTables.js
  363:14:syntax error
[ERROR] in DataTables.js
  365:22:syntax error
[ERROR] in DataTables.js
  366:26:syntax error
[ERROR] in DataTables.js
  367:14:syntax error
[ERROR] in DataTables.js
  368:22:syntax error
[ERROR] in DataTables.js
  370:13:syntax error
[ERROR] in DataTables.js
  371:30:syntax error
[ERROR] in DataTables.js
  373:25:syntax error
[ERROR] in DataTables.js
  389:13:syntax error
[ERROR] in DataTables.js
  392:5:syntax error
[ERROR] in DataTables.js
  393:1:syntax error
[ERROR] in DataTables.js
  395:9:syntax error
[ERROR] in DataTables.js
  1:0:Compilation produced 28 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 28 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

Process finished with exit code 2```

**Comment by jinliming2** [comment]
Is this project still alive?

**Comment by Chris2011** [comment]
@jinliming2  As you can see, they merged some PRs some days/weeks ago. But no real effort on this project anymore(?). @tml can you explain the state here? Waiting for smth or change smth or what? Can you clarify that please?

**Comment by yoshicode** [comment]
+1

**Comment by jkeam** [comment]
Proj is dead?

**Comment by kcak11** [comment]
Looks like is dead long back. RIP yuicompressor

**Comment by iileandro** [comment]
+1!

**Comment by iileandro** [comment]
Guys, someone here found an alternative (jar lib) to yuicompressor with ES6?

**Comment by kcak11** [comment]
> Guys, someone here found an alternative (jar lib) to yuicompressor with ES6 support?

As far as I have researched, I believe yuicompressor is a pretty old library which is not being maintained anymore and hence it does not cater to ES6 and the newer syntaxes.

If you are really looking for JS compression, then probably you will have to look for alternative bundling approaches like [webpack](https://webpack.js.org/), [javascript-minifier](https://javascript-minifier.com), [jscompress](https://jscompress.com), etc.,.

**Comment by iileandro** [comment]
Yep. I got tesser (npm based). It saved me. The only one I've tested that was able to ES6 at all! I call the command from java stead of YUICompressor lib call.

**Comment by kcak11** [comment]
I believe you meant [terser](https://www.npmjs.com/package/terser)

**Comment by iileandro** [comment]
yep. Sorry!

**Comment by zetekla** [comment]
You can use gcc
GCC - Google Closure Compiler (iirc) is what we use for an AEM app, which
at time I want to allow. es6 compiled code to pass compilation process and
deploy successfully.

Regards
Pristine

**Comment by zetekla** [comment]
You can use gcc
Google Closure Compiler (iirc) is what we use

**Comment by DougBaughman** [comment]
Is there a maven plugin for Google Closure Compiler?  LIke yuicompressor-maven-plugin

**Comment by Chris2011** [comment]
> Is there a maven plugin for Google Closure Compiler? LIke yuicompressor-maven-plugin

https://mvnrepository.com/artifact/com.google.javascript/closure-compiler @DougBaughman ;)

**Comment by DougBaughman** [comment]
Thanks @Chris2011, but I'm looking for  a Maven plug-in (mojo), not just a dependency.  I want something that will minify javascript automatically as part of a maven build.  LIke http://davidb.github.io/yuicompressor-maven-plugin/ does with yuicompressor
