### ISSUE TITLE
Compressing code with "native" keyword as an object attributes fails

### ISSUE THREAD

**Issue by sandvige** [yui/yuicompressor#288]
Considering this code:
``` js
var a = {};
a.native = 12;
console.log(a);
```

We have this error when compressing:
```
xxx@xxx:~/xxx$ java -jar java/yuicompressor.jar --charset UTF-8 --type js x.js
[ERROR] in x.js
  2:9:missing name after operator '.'
[ERROR] in lol.js
  1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
        at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
        at org.mozilla.javascript.Parser.parse(Parser.java:396)
        at org.mozilla.javascript.Parser.parse(Parser.java:340)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

YUICompressor Version: 2.4.8

**Comment by sandvige** [comment]
Probably a deplucate of this issue, but the title wasn't very clear at first look :)
