### ISSUE TITLE
yuicompressor  issue error 

### ISSUE THREAD

**Issue by githubafc** [yui/yuicompressor#307]
1:0:Compilation produced 10 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 10 syntax erro
        at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUIC
        at org.mozilla.javascript.Parser.parse(Parser.java:396)
        at org.mozilla.javascript.Parser.parse(Parser.java:340)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaSc
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaS
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImp
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcc
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

**Comment by dilmerv** [comment]
Similar error here:

[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  3845:9:missing name after . operator
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  3846:11:syntax error
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  3847:5:missing ; before statement
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  3850:2:missing ) after argument list
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  8783:27:missing name after . operator
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  8784:17:syntax error
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  8800:8:invalid return
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  8800:34:missing ; before statement
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  10363:7:invalid return
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  10364:1:syntax error
[ERROR] in /Users/dvalecillos/Desktop/JS (JAVASCRIPT)/jquery.js
  1:0:Compilation produced 10 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 10 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)

**Comment by mathieuhecker** [comment]
Did you have any response for this issue ?

**Comment by milkovsky** [comment]
the same here
```
[ERROR] in -
  1:0:Compilation produced 930 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 930 syntax errors.
        at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
        at org.mozilla.javascript.Parser.parse(Parser.java:396)
        at org.mozilla.javascript.Parser.parse(Parser.java:340)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
2019-09-19 16:30:19: [  DEBUG  ] strg.yui.compressor.YuiMinifier.class:process() [61]: 
2019-09-19 16:30:19: [  DEBUG  ] strg.yui.compressor.YuiMinifier.class:process() [62]: [ERROR] in -```
