### ISSUE TITLE
for(let k of data){}

### ISSUE THREAD

**Issue by baiyukey** [yui/yuicompressor#318]
`let data=[{a:1,b:2},{a:2,b:3}];
for(let k of data){
//...
}`

Output error:
.....
at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

**Comment by KingFishTheKing** [comment]
I think YUI can't handle 'let', try 'var' instead
