### ISSUE TITLE
Unable to specify absolute path for output file.

### ISSUE THREAD

**Issue by altearius** [yui/yuicompressor#78]
In 2.4.7, it was possible to specify an absolute path for the output file.  Attempting to do this in 2.4.8 causes the following error:

```
java -jar "C:\Path\To\yuicompressor-2.4.8.jar" --charset UTF-8 --type js -o "C:\outputfile.min.js" "C:\path\to\source\file.js"

java.io.FileNotFoundException: outputfile.min.js:\path\to\source\file.js (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:183)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

**Comment by labkey-adam** [comment]
Am I missing something here? Didn't @maskamar fix this issue a year and a half ago with 350933e2ef1651b3631ea4b1898b8e40f9f18aaf? In our product build, 2.4.8 fails on Windows with absolute paths but yuicompressor built from master seems to handle them fine. Any further fixes or testing required before closing this issue?

**Comment by maskamar** [comment]
There is a feature that cause this problem.

"-o outfile
   ...
    Supports a filter syntax for expressing the output pattern when there are
    multiple input files.  ex:
        java -jar yuicompressor.jar -o '.css$:-min.css' *.css
    ... will minify all .css files and save them as -min.css"

This feature splits output path with colon and handle it like multiple input files. So C:\somename.css is split to C and \somename.css and application looking for files with "C" in filename. I added condition to prevent this feature for path starting with c:\ (and also for other letters). Yeah, it is that simple.

I also fixed issue https://github.com/yui/yuicompressor/issues/130 with https://github.com/yui/yuicompressor/commit/98eb2c0e6632bc26a274af7478d3c0ce44544981 no one cares and people still have those problems. :-1:

**Comment by labkey-adam** [comment]
Well, @maskamar, I care. We use a very old version of this library in our build, I attempted an upgrade, encountered this issue, and cloned the repo looking to fix the problem myself... but, of course, you already took care of it. Thank you for that!

Perhaps the fix wasn't noticed because this issue was left open with no reference to your commit? Regardless, I'd be happy to help push out a new release (2.4.9?) to get your fixes and others to the community.

**Comment by tml** [comment]
@maskamar It's untrue that no one cares; however, as @labkey-adam notes, there's nothing in here that shows me your suggested fix, so I'm not sure what you would like me to do? There was a period of time where a mistake by the Yahoo folks unassigned all tickets away from me, and GitHub didn't notify me, so it took a few months for me to notice it had happened. Perhaps you sent a PR in that timeline and then retracted it or something?

**Comment by cecekpawon** [comment]
Those who are still having the same problem, seems they just download from [outdated](https://github.com/yui/yuicompressor/releases) binary releases / not compile it by hand. [Here](
http://1drv.ms/1PdnQSE) to test, compiled version from OSX 10.11 & Windows 10 with Ant 1.9.4 & jdk-8u66-64 from latest commits in this repo. Once it run without this bugs, please start to replace old 2.4.8 zip released, so peoples can instantly download & run it without any problem.

**Comment by casman300** [comment]
Ok so was having this same issue, have a temp solution....

cd "%Full-path-to-output-folder%"
java -jar %full-path-to\yuicompressor-2.4.8.jar% %Full-path-to-input-file-demo.js% -o demo.min.js

Hopefuly this helps someone else for now.

**Comment by bnadji** [comment]
Just ran into this issue.  

These comments were helpful to me to find out why the problem exists to begin with - especially comment by **maskamar** on oct 31, 2015. Since the new code is not yet jar'd, I downloaded the fixed source and used **ant 1.10.1** to build it.  It produced version **yuicompressor-2.4.9. jar **   which I have used for a few days with no problems.  The absolute path issue is gone.

In my copy, I also updated the **--help** option under **-o \<file\>** to reflect the fact that this version does not support split filter syntax for absolute paths that start with drive name and a ":", such as C:\dir\filename.js etc.

Thanks for the useful comments.  BTW, the link in **cecekpawon** Oct 31, 2015 comment is broken.  

Would 2.4.9 be officially released any time soon?

**Comment by altearius** [comment]
Since the last release (2.4.8) was four years ago, I wouldn't hold my breath.  I don't know for sure, but I would guess that YUI Compressor is included as part of this announcement: https://yahooeng.tumblr.com/post/96098168666/important-announcement-regarding-yui

Since you seem to have a working build of 2.4.9, perhaps you should fork the project and make your build more generally available.  If you do so, it will probably be the most meaningful advance of YUI in years.

**Comment by bnadji** [comment]
@altearius 
I've made enhancements in yuicompressor-2.4.9 to solve the (colon ':' in file/pathname ) problem in a more generic way.   The fix in this release is adding a new option `-s <char>`  where char is a new character used (in place of ':') for splitting output file name.  For example if we chose "@" as the new character, one can safely use the following to process a batch of javascript files:

`java -jar yuicompressor-2.4.9.jar -s @ -o ".js$@-min.js" C:\dir\*.js`

or in a single file compression scenario:

`java -jar yuicompressor-2.4.9.jar -s @ -o C:\dir1\outfile.js C:\dir2\infile.js`

So the -s option now appears to solve the issues that were discussed on this forum. I have also added two other options:

`-w, --no-style-warning` to suppress coding style warnings generated by the compressor, such as,   
  "[WARNING] Using 'eval' is not recommended."  After all, why should a compressor complain about coding style?

`-W --no-warning` to suppress all warnings.  Good when compressing third party code.

`-v --verbose` was also enhanced and is more verbose and actually useful now.

Usage() is also updated. I have tested it on over 100 files under windows and unix shell and It is working as advertised. I am not a pro githubber and haven't done any forks here.  But I have the modified sources and the new ` yuicompressor-2.4.9.jar`  available on [this link](https://1drv.ms/f/s!Avdtun4lMpKBc6mk9yAW0LDuSPg) for whoever can take it over and make it an official release, or if you just want to download and use it.
Reg,
Brad

CC: @maskamar, @tml , @roblarsen , @Leonya , @labkey-adam

**Comment by nagyimre1980** [comment]
> @altearius Fejlesztéseket végeztem a yuicompressor-2.4.9-ben, hogy általánosabb módon oldjam meg a (kettőspont ':' a fájl/elérési útnévben) problémát. Ebben a kiadásban a javítás egy új beállítást ad, `-s <char>` ahol a char egy új karakter, amelyet (a „:” helyett) használnak a kimeneti fájlnév felosztására. Például, ha a "@"-t választottuk új karakterként, biztonságosan használhatja a következőket egy köteg JavaScript-fájl feldolgozásához:
> 
> `java -jar yuicompressor-2.4.9.jar -s @ -o ".js$@-min.js" C:\dir\*.js`
> 
> vagy egyetlen fájl tömörítési forgatókönyv esetén:
> 
> `java -jar yuicompressor-2.4.9.jar -s @ -o C:\dir1\outfile.js C:\dir2\infile.js`
> 
> Tehát úgy tűnik, hogy a -s opció megoldja a fórumon megvitatott problémákat. Két további lehetőséget is hozzáadtam:
> 
> `-w, --no-style-warning`a tömörítő által generált kódolási stílus figyelmeztetések elnyomására, például: "[FIGYELMEZTETÉS] Az "eval" használata nem javasolt." Végül is miért panaszkodhatna egy kompresszor a kódolási stílusra?
> 
> `-W, --no-warning`hogy elnyomjon minden figyelmeztetést. Harmadik fél kódjának tömörítéséhez jó.
> 
> `-v, --verbose`is továbbfejlesztett, és bőbeszédűbb, és most már valóban hasznos.
> 
> A Usage() is frissül. Több mint 100 fájlon teszteltem Windows és unix shell alatt, és a hirdetett módon működik. Nem vagyok profi githubber, és nem csináltam itt semmilyen fork-ot. [De ezen a linken](https://1drv.ms/f/s!Avdtun4lMpKBc6mk9yAW0LDuSPg)` yuicompressor-2.4.9.jar` elérhetőek a módosított források és az új, aki át tudja venni és hivatalos kiadássá tudja tenni, vagy csak letölteni és használni szeretné. Reg, Brad[](https://1drv.ms/f/s!Avdtun4lMpKBc6mk9yAW0LDuSPg)
> 
> CC:@maskamar,@tml,@roblarsen,@Leonya,@labkey-adam

can you send me the jar file?
